name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build 1.9.2 Docker image
      run: cd diann-1.9.2/; docker build . --file Dockerfile --tag diann:1.9.2
    - name: Build 2.0 Docker image
      run: cd diann-2.0/; docker build . --file Dockerfile --tag diann:2.0
